# Generated by Django 4.0.1 on 2022-09-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='spoc',
            field=models.JSONField(blank=True, null=True, verbose_name='HR Details'),
        ),
    ]
